files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  brace-style: 0
  function-name-format:
    - 0
    - allow-leading-underscore: true
      convention: camelcase
  hex-length: 0
  hex-notation:
    - 1
    - style: uppercase
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: false
  mixin-name-format:
    - 0
    - allow-leading-underscore: true
      convention: camelcase
  nesting-depth:
    - 0
    - max-depth: 4
  no-css-comments: 1
  placeholder-name-format:
    - 0
    - allow-leading-underscore: true
      convention: camelcase
  property-sort-order:
    - 1
    - ignore-custom-properties: true
      order:
        - z-index
        - visibility
        - opacity
        - display
        - flex-direction
        - align-items
        - position
        - top
        - right
        - bottom
        - left
        - float
        - clear
        - overflow
        - null
        - width
        - min-width
        - max-width
        - height
        - min-height
        - max-height
        - null
        - border
        - border-top
        - border-right
        - border-bottom
        - border-left
        - border-width
        - border-top-width
        - border-right-width
        - border-bottom-width
        - border-left-width
        - border-style
        - border-top-style
        - border-right-style
        - border-bottom-style
        - border-left-style
        - border-radius
        - border-top-left-radius
        - border-top-right-radius
        - border-bottom-left-radius
        - border-bottom-right-radius
        - border-color
        - border-top-color
        - border-right-color
        - border-bottom-color
        - border-left-color
        - box-shadow
        - null
        - font
        - font-family
        - font-size
        - font-weight
        - font-smoothing
        - font-style
        - null
        - transform
        - transition
        - null
        - animation
        - animation-name
        - animation-duration
        - animation-timing-function
        - animation-delay
        - animation-iteration-count
        - animation-direction
        - animation-fill-mode
        - animation-play-state
  quotes:
    - 1
    - style: single
  single-line-per-selector: 0
  space-before-brace:
    - 0
    - include: true
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 0
  variable-name-format:
    - 0
    - allow-leading-underscore: true
      convention: camelcase
  zero-unit: 1
